### ISSUE TITLE
inko --help does not show check in command list

### ISSUE THREAD

**Issue by MarcusE1W** [inko-lang/inko#652]
### Please describe the bug

More an observation than a real bug.
`inko --help` does not show `check` in the list of possible commands. 
It is mentioned in the examples though.

Feel free to close if this is not important right now.

### Please list the exact steps necessary to reproduce the bug

inko --help

### Operating system

Archlinux

### Inko version

0.13.1

### Rust version

1.72

**Comment by yorickpeterse** [comment]
The fix is to simply add it to this list: https://github.com/inko-lang/inko/blob/8d3c6ef38ba50927e295017b96055883ecddbf6d/inko/src/command/main.rs#L16-L20

While we're at it, we should probably sort that list alphabetically for the sake of consistency.

This should be an easy issue for those looking to get started with helping out, so I've added the "accepting contributions" label to signal that.
