### ISSUE TITLE
Avoid the use of LLD when it's installed but the target isn't supported by LLD

### ISSUE THREAD

**Issue by MarcusE1W** [inko-lang/inko#654]
### Please describe the bug

When I build the demo hello.inko file with `inko build hello.inko` I get a linker error for lld on a Pinebook Pro with aarch64 ARM architecture.

Error message:
```
The linker exited with status code 1:
ld.lld: error: unknown argument '--fix-cortex-a53-835769'
collect2: error: ld returned 1 exit status
```

Inko uses llvm 15 which is installed, but for lld there is only version 16.0.6 available. Is that possibly the reason?

If that is the case, in the docu it is mentioned that lld is optional. How can I not use the lld16 version and what would I use instead?

Versions:
llvm 15.0.7 (and llvm14, llvm16)
lld 16.0.6
gcc 12.01

### Please list the exact steps necessary to reproduce the bug

inko build hellp.inko

### Operating system

Archlinux ARM

### Inko version

0.13.1

### Rust version

1.73

**Comment by yorickpeterse** [comment]
@MarcusE1W The flag isn't set by Inko. I don't think the lld version would matter though, because it just links object files and doesn't care about e.g. LLVM IR version differences.

[This bug report](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=105941) suggests that perhaps on your setup the compiler (whatever `cc` ends up calling) passes this option under the assumption lld supports it.

I'm guessing we'd need a way to not only figure out if lld is installed (which we already have), but if it also supports whatever options the compiler passes to it. The problem here is that we don't know what options are passed by the compiler to the linker, so we also don't know which ones to check for :thinking:

**Comment by yorickpeterse** [comment]
Per `ld.lld --help`:

```
ld.lld --help | rg fix-cortex
  --fix-cortex-a53-843419 Apply fixes for AArch64 Cortex-A53 erratum 843419
  --fix-cortex-a8         Apply fixes for ARM Cortex-A8 erratum 657417
```

So it seems two of these options are supported, but the one used here isn't, and that's using LLD 16.0.6.

https://github.com/llvm/llvm-project/issues/30256 discusses adding the `--fix-cortex-a53-843419` flag, but from what I understand `--fix-cortex-a53-835769` just won't be supported.

**Comment by yorickpeterse** [comment]
For this specific case we could somehow detect the use of a Cortex A53, but such an approach will get out of hand as the number of exceptions increases. We also can't test for such a specific case in CI as we don't run tests on this hardware, so we need a more generic "can we use lld?" check, somehow.

**Comment by yorickpeterse** [comment]
@MarcusE1W On this Cortex device, could you try the following:

1. Download [654.tar.gz](https://github.com/inko-lang/inko/files/13370173/654.tar.gz) and save it somewhere
2. Run `mkdir 654 && tar -xvf 654.tar.gz -C 654 && cd 654 && cargo run`
3. This prints something along the lines of `CPU: "..."` (e.g. `CPU: "skylake"` for me). Can you share that line here?

My thinking is that if that prints something like "cortex", then we could use that to disable the use of lld automatically. Thanks!

**Comment by MarcusE1W** [comment]
The output from that tool is `CPU: "cortex-a72"`.
Cortex is used for many  ARM CPUs. The A stands for a full CPU where a M would indicate a microprocessor.

For explanation, my Rockchip RK3399 ARM CPU has 4xA53 energy efficient "slow" cores and 2xA72 performance cores.

In the meantime I have just removed lld16 and the program now runs successfully.

**Comment by yorickpeterse** [comment]
@MarcusE1W Thanks! I suppose we could detect that value and disable the use of LLD automatically.

I'll rename this issue to better reflect that on certain configurations we may need to disable the use of LLD if it's installed. While for this specific case we can check for that value and assume LLD just won't work with `cortext-a72`, but I suspect more (and different) cases may present themselves over time. As such, I'll probably leave this be for a bit to see if more similar cases present themselves over time.

**Comment by yorickpeterse** [comment]
Adding a note for myself or future contributors:

To obtain this information, we'd need to use Inkwell's `inkwell::targets::TargetMachine::get_host_cpu_name()` method, but in such a way that it's scoped to the target we're compiling to, rather than blindly using the _host_ CPU name, as the two may differ. Inkwell's `TargetMachine` type has the [`get_cpu()`](https://thedan64.github.io/inkwell/inkwell/targets/struct.TargetMachine.html#method.get_cpu) instance method, but when I tried it I believe it either returned an empty string or just "x86-64", neither of which are helpful.

In light of https://github.com/inko-lang/inko/issues/524, we may also need a better mechanism to switch the linker in general. For example, if I'm cross-compiling from Linux to some other platform, I might need a linker specific to that platform. 

Assuming `cc`/`gcc`/`clang` etc can figure that out automatically based on some `--target` flag of sorts, it might be better to just default to the system linker and make using LLD a configuration flag, even though I really dislike such configuration flags. Alternatively, we could just disable LLD if we're compiling for a target other than the host target, or when compiling to ARM since it's usually ARM chips that need weird configuration settings.

**Comment by MarcusE1W** [comment]
Happy to report that it works now.
